In [51]:
import numpy as np
import pandas as pd
import sklearn as sk
import convertDictionaries as cd

#import classifiers
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

#import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, balanced_accuracy_score, roc_auc_score, f1_score

In [52]:
data = pd.read_csv("./finalfinalDataset.csv")

In [53]:
y = pd.read_csv('./output_tidy.csv').drop('Unnamed: 0', axis=1)

In [54]:
data.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       ...
       'wnioskowania', 'wolicjonalny', 'wolitywny', 'zdarzeniowy', 'o1+',
       'o1-', 'o1o', 'o2+', 'o2-', 'o2o'],
      dtype='object', length=325)

In [55]:
data = data.drop(["index", 'Unnamed: 0', 'verb'], axis=1)

In [56]:
y_onehot = data.iloc[:, -6:]

In [57]:
X = data.iloc[:, :-6]

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.1)

In [75]:
estimators = [
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    RandomForestClassifier(), 
    MLPClassifier(),
    AdaBoostClassifier(),
    GaussianProcessClassifier(),
    GradientBoostingClassifier(),
    SVC(kernel="linear"),
    SVC(kernel="rbf")
]

In [76]:
cross_val_score(estimators[0], X, y_onehot, cv=5)

array([0.64347826, 0.80701754, 0.73684211, 0.73684211, 0.71929825])

In [77]:
model = estimators[0].fit(X_train, y_train)

In [78]:
model.score(X_test, y_test)

0.8620689655172413

In [84]:
prediction = model.predict(X_test)

In [100]:
def precision(y, y_pred):
    p1=(y_pred[:, :3] * y[:, :3]).sum()/y_pred[:,:3].sum()
    p2=(y_pred[:, 3:] * y[:, 3:]).sum()/y_pred[:,3:].sum()
    return p1, p2
def recall(y, y_pred):
    p1=(y_pred[:, :3] * y[:, :3]).sum()/y[:,:3].sum()
    p2=(y_pred[:, 3:] * y[:, 3:]).sum()/y[:,3:].sum()
    return p1, p2

In [101]:
precision(y_test.to_numpy(), prediction)

(0.8793103448275862, 0.9137931034482759)

In [102]:
recall(y_test.to_numpy(), prediction)

(0.8793103448275862, 0.9137931034482759)

In [115]:
prediction[:,:3].sum()

58

In [116]:
prediction[:,3:].sum()

58

In [117]:
y_test.to_numpy()[:,3:].sum()

58

In [118]:
y_test.to_numpy()[:,:3].sum()

58

In [113]:
y_test.to_numpy()[:,:3] - y_test.to_numpy()[:,3:]

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 1,  0, -1],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [-1,  0,  1],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  

In [114]:
prediction[:,3:] - prediction[:,:3] 

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 1,  0, -1],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  

In [119]:
y_test - prediction

o1+  o1-  o1o  o2+  o2-  o2o
192    0    0    0    0    0    0
111    0    0    0    0    0    0
187    0    0    0    0    0    0
488    0    0    0    0    0    0
301    0    0    0    0    0    0
467    0    1   -1    0    0    0
314    0    0    0    0    0    0
504    0    0    0    0    0    0
444    0    0    0    0    0    0
379    0    0    0    0    0    0
495    0    0    0    0    0    0
293    0    0    0    0    0    0
158    0    0    0    0    0    0
221    0    0    0    0    0    0
7     -1    0    1   -1    0    1
369    0    0    0    0    0    0
342    0    0    0    0    0    0
476    0    0    0    0    0    0
83     0    0    0    0    0    0
390    0    0    0   -1    0    1
209    0    0    0    0    0    0
450    0    0    0    0    0    0
44     0    0    0    0    0    0
205    0    0    0    0    0    0
19     0    0    0    0    0    0
540    0    0    0    0    0    0
53     0    0    0    0    0    0
270    0    0    0    0    0    0
263    0    0    0    0    0    0
372    0    0    0    0    0    0
443    1    0   -1    1    0   -1
332    0    0    0    0    0    0
143    0    0    0    0    0    0
519    0    0    0    0    0    0
92     0    0    0    0    0    0
494    0    0    0    0    0    0
268    0    0    0    0    0    0
496    0    0    0    0    0    0
570    0    0    0    0    0    0
119    0    0    0    0    0    0
58     0    0    0    0    0    0
269    0    0    0    0    0    0
486    0    0    0    0    0    0
384    0    0    0    0    0    0
18     0    0    0    0    0    0
50     0    0    0    0    0    0
76     0    0    0    0    0    0
280    0    0    0    0    0    0
376    0    0    0    0    0    0
277    1   -1    0    0    0    0
438    0    0    0    0    0    0
431   -1    0    1   -1    0    1
516    0    0    0    0    0    0
319    0    0    0    0    0    0
398   -1    0    1    0    0    0
160    0    0    0    0    0    0
106   -1    0    1   -1    0    1
148    0    0    0    0    0    0